instagram/blueprints/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField, BooleanField, validators


class NewUserForm(FlaskForm):

    username = StringField('Username:')
    email = StringField('Email:')
    password = PasswordField('Password:')
    submit = SubmitField('Add User')


class EditUserForm(FlaskForm):

    username = StringField('Username:')
    email = StringField('Email:')
    description = TextAreaField('Description:')
    private = BooleanField('Make Private')
    submit = SubmitField('Update Information')

class SearchUserForm(FlaskForm):

    username = StringField('Username:', [validators.InputRequired()])
    submit = SubmitField('Search')

instagram/blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user
from models.user import User
from instagram.blueprints.users.forms import NewUserForm, EditUserForm
from instagram import app, db
from instagram.helpers.image_uploader import upload_file_to_s3, allowed_profile_images, delete_file_from_s3
from werkzeug.utils import secure_filename
from instagram.helpers.braintree import gateway


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates/users')


@users_blueprint.route('/new', methods=['GET'])
def new():
    if current_user.is_authenticated:
        return redirect(url_for('users.edit', id=current_user.id))

    form = NewUserForm()
    return render_template('new.html', form=form)


@users_blueprint.route('/', methods=['POST'])
def create():
    form = NewUserForm(request.form)

    user = User(username=form.username.data,
                email=form.email.data,
                password=form.password.data)

    if len(user.validation_errors) > 0:
        return render_template('new.html', validation_errors=user.validation_errors, form=form)
    else:
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f"Welcome {user.username}")
        return redirect(url_for('users.show', username=user.username))


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.query.filter_by(username=username).first()

    if user:
        client_token = gateway.client_token.generate()

        allowed_to_view_profile = \
            (current_user.is_authenticated and current_user.id == user.id) or \
                current_user in user.fans or \
                not user.private


        images = user.images
        return render_template('show.html', user=user, allowed_to_view_profile=allowed_to_view_profile, client_token=client_token, images=images)


@users_blueprint.route('/', methods=["GET"])
def index():
    users = User.query.all()
    return render_template('index.html', users=users)


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    edit_user_form = EditUserForm(obj=current_user)
    return render_template('edit.html', user=current_user, form=edit_user_form)


@users_blueprint.route('/<id>', methods=['POST'])
@login_required
def update(id):
    form = EditUserForm(request.form)

    user = User.query.get(id)

    # Prevent unauthorized user from changing data of another user
    if not user.id == current_user.id:
        return render_template('edit.html', validation_errors=['Unauthorized!'], form=form, user=user)

    user.username = form.username.data
    user.email = form.email.data
    user.description = form.description.data
    user.private = form.private.data

    if len(user.validation_errors) > 0:
        return render_template('edit.html', validation_errors=user.validation_errors, form=form, user=user)
    else:
        db.session.add(user)
        db.session.commit()
        flash('Information updated!')
        return redirect(url_for('users.show', username=user.username))


@users_blueprint.route('/<id>/profile/image', methods=['POST'])
@login_required
def upload_profile_image(id):
    form = EditUserForm()

    user = User.query.get(id)

    # Prevent unauthorized user from changing data of another user
    if not user.id == current_user.id:
        return render_template('edit.html', validation_errors=['Unauthorized!'], form=form, user=user)

    if "profile_image" not in request.files:
        flash("No profile image")
        return render_template('edit.html', validation_errors=[], form=form, user=user)

    file = request.files["profile_image"]

    if file.filename == "":
        flash("Please select a file")
        return render_template('edit.html', form=form)

    if file and allowed_profile_images(file.filename):
        old_filename = user.profile_picture
        delete_file_from_s3(old_filename, app.config["S3_BUCKET"])

        file.filename = secure_filename(user.username + "-" + file.filename)
        output = upload_file_to_s3(file, app.config["S3_BUCKET"])
        user.profile_picture = file.filename

        db.session.add(user)
        db.session.commit()


        flash("Profile Picture Updated!")

        return redirect(url_for('users.show', username=user.username))

    else:
        return redirect("/")

@users_blueprint.route('/search', methods=['POST'])
def search():
    username = request.form["username"]
    user = User.query.filter(User.username.ilike(f'%{username}%')).first()

    return redirect(url_for("users.show", username=user.username))

instagram/blueprints/users/templates/users/edit.html
{% extends "_base.html" %}
{% block content %}
  <div class="row">
    <div class="col">
      <h2>Edit User</h2>

      <form action={{url_for("users.update", id=current_user.id)}} method="POST">
        {% for error in validation_errors %}
          <li>{{error}}</li>
        {% endfor %}
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.csrf_token() }}
        <div class="form-group">
          {{ form.username.label }} {{ form.username(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.email.label }} {{ form.email(class="form-control") }}
        </div>
        <div class="form-group form-check">
          {{ form.private(class="form-check-input") }}
          {{ form.private.label(class="form-check-label") }}
        </div>
        <div class="form-group">
          {{ form.description.label }} {{ form.description(class="form-control") }}
        </div>
        {{ form.submit(class="btn btn-primary") }}
      </form>
    </div>
  </div>


  <div class="row">
    <div class="col">
      <h2>Change Your Profile Picture</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      {% if user.profile_picture %}
        <img src="{{user.profile_picture_url}}" class="profile-picture-edit rounded float-left" alt="{{user.username}}-profile-picture"/>
      {% else %}
        <img src="https://s3.amazonaws.com/next-curriculum-instagram/profile-placeholder.jpg" class="profile-picture-edit rounded float-left" alt="{{user.username}}-profile-picture"/>
      {% endif %}
    </div>
    <div class="col-9">
      <form action={{url_for("users.upload_profile_image", id=current_user.id)}} method="POST" enctype="multipart/form-data">
        <input type="file" name="profile_image">
        <button class="btn btn-primary" type="submit">Upload</button>
      </form>
    </div>
{% endblock %}

instagram/blueprints/users/templates/users/index.html
{% extends "_base.html" %}
{% block title %}Nextagrammers | {% endblock %}
{% block content %}
  {% for user in users %}
    <div class="row border border-0 mb-5 rounded pt-3 pb-3 user-index-feature">
      <div class="col-sm-2 mb-5">
        <a href={{url_for("users.show", username=user.username)}} class="font-weight-bold">{{user.username}}</a>
        <p class="mt-3 mb-3 card-text">{{user.description}}</p>
        <img src="{{user.profile_picture_url}}" class="users-index-profile-images rounded-circle mb-5" />
        <a href="{{url_for('users.show', username=user.username)}}" class='btn btn-primary btn-block'>See More</a>
      </div>
      <div class="col">
        {% if user.images | length > 0 %}
          <div class="row">
            {% for image in user.images %}
              <div class="col-sm-4 mb-2">
                <img src="{{image.image_url}}" alt="{{image.image_name}}"  class="img-fluid feed-picture"/>
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
  {% endfor %}
{% endblock %}

instagram/blueprints/users/templates/users/new.html
{% extends "_base.html" %}
{% block title %}New User | {% endblock %}
{% block content %}
  <h2>New User</h2>
  <form action={{url_for("users.create")}} method="POST">
    {% for error in validation_errors %}
      <li>{{error}}</li>
    {% endfor %}
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.csrf_token() }}
    <div class="form-group">
      {{ form.username.label }} {{ form.username(class="form-control") }}
    </div>
    <div class="form-group">
    {{ form.email.label }} {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label }} {{ form.password(class="form-control") }}
    </div>
    {{ form.submit(class="btn btn-primary") }}
  </form>
{% endblock %}

instagram/blueprints/users/templates/users/show.html
{% extends "_base.html" %}
{% block title %}{{user.username}} | {% endblock %}
{% block header %}
  <script src="https://js.braintreegateway.com/web/dropin/1.14.1/js/dropin.min.js"></script>
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row mb-5">
    <div class="col-sm-3">
      <img src="{{user.profile_picture_url}}" alt="{{user.username}} profile picture" class="img-fluid profile-picture-show" />
    </div>
    <div class="col-6">
      <h2 class="mt-3">@{{user.username}}</h2>
      <p class="mt-3">{{user.description | default("", true)}}</p>
    </div>
    <div class="col-sm-3">
      {% if current_user.id == user.id %}
        <form action={{url_for("images.create")}} method="POST" enctype="multipart/form-data">
          <div class="form-group">
            <input class="form-control-file" type="file" name="image">
          </div>
          <button class="btn btn-primary" type="submit">Post Image</button>
        </form>
      {% endif %}

      {% if not current_user.id == user.id and (user in current_user.follow_requests) %}
        <span class="badge badge-secondary">Requested</span>
      {% elif current_user.is_authenticated and not current_user.id == user.id and (not user in current_user.idols) %}
        <form action={{url_for("followings.create")}} method="POST">
          <input type="hidden" name="idol_id" value="{{user.id}}" />
          <button class="btn btn-primary float-right" type="submit">Follow</button>
        </form>
      {% elif current_user.is_authenticated and not current_user.id == user.id %}
        <form action={{url_for("followings.destroy", idol_id=user.id)}} method="POST">
          <button class="btn btn-secondary float-right" type="submit">Unfollow</button>
        </form>
      {% endif %}
    </div>
  </div>

  {% if images | length > 0 and allowed_to_view_profile %}
    <div class="row">
      {% for image in user.images %}
        <div class="col-sm-4 mb-2">
          <img src="{{image.image_url}}" alt="{{image.image_name}}"  class="img-fluid feed-picture"/>

          {% if current_user.id == user.id %}
            <form action="{{url_for('images.destroy', id=image.id)}}" onSubmit="return confirm('Are you sure you wish to delete?');" method="POST">
                <input type='submit' value='Delete' class='btn btn-outline-danger'/>
            </form>
          {% endif %}

          {% if current_user.is_authenticated and current_user.id != user.id %}
            <button class="donate btn btn-primary" type="button" value="{{image.id}}" onClick="startDonation(this)">Donate</button>
          {% elif current_user.id != user.id %}
            <button class="donate btn btn-secondary" type="button" value="{{image.id}}">Donate</button>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}


  <div class="modal fade" id="creditCardFormModal" tabindex="-1" role="dialog" aria-labelledby="creditCardFormModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="creditCardFormModalLabel">Your generosity is much appreciated</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="creditCardForm" class="modal-body">
            <form id="donationForm" action="{{url_for('donations.create')}}" method="POST">
              <input type="hidden" name="image_id" />
              <div class="form-group">
                <label for='amount'>How much would you like to donate?</label>
                <input class="form-control" type='tel' name='amount' min="1" placeholder="5"/>
              </div>
              <input type="hidden" id="nonce" name="payment_method_nonce" />
              <div class="bt-drop-in-wrapper">
                <div id="bt-dropin"></div>
              </div>
              <button class="button btn btn-primary" type="submit" id="submit-button"><span>Confirm Donation</span></button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    var donationForm = document.querySelector('#donationForm');

    function startDonation(button) {
      const imageId = button.value
      donationForm.elements["image_id"].value = imageId
      $('#creditCardFormModal').modal()
    }

    var client_token = '{{ client_token }}';

    braintree.dropin.create({
      authorization: client_token,
      container: '#bt-dropin'
    }, function (createErr, instance) {
      donationForm.addEventListener('submit', function (event) {
        event.preventDefault();
        instance.requestPaymentMethod(function (err, payload) {
          if (err) {
            console.log('Error', err);
            return;
          }
          // Add the nonce to the form and submit
          document.querySelector('#nonce').value = payload.nonce;
          donationForm.submit();
        });
      });
    });
  </script>

  {% if user.private %}
    <p class="text-center font-italic">This profile is private</p>
  {% endif %}

</div>
{% endblock %}