instagram/blueprints/feed/views.py
from flask import Blueprint, render_template
from flask_login import current_user


feed_blueprint = Blueprint('feed',
                            __name__,
                            template_folder='templates')


@feed_blueprint.route('/', methods=['GET'])
def index():
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    images_feed = current_user.images_feed

    return render_template('feed/index.html', images_feed=images_feed)

instagram/blueprints/followings/views.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_login import current_user
from models.user import User

followings_blueprint = Blueprint('followings',
                            __name__,
                            template_folder='templates')


@followings_blueprint.route('/', methods=['GET'])
def show():
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    return render_template('followings/show.html')

@followings_blueprint.route('/', methods=['POST'])
def create():
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    fan_id = request.form.get('fan_id')

    if fan_id:
        fan = User.query.get(fan_id)
        if fan and current_user.approve(fan):
            print("------------")
            flash(f"You've approved {fan.username}")
            return redirect(request.referrer)

    idol = User.query.get(request.form['idol_id'])

    if idol and current_user.follow(idol) == 'Your request has been sent':
        flash(f"Your request to follow {idol.username} has been sent")
        return redirect(request.referrer)

    elif idol and current_user.follow(idol):
        flash(f"Successfully followed {idol.username}")
        return redirect(request.referrer)

    flash("Failed to follow user")
    return redirect(request.referrer)

@followings_blueprint.route('/<idol_id>', methods=['POST'])
def destroy(idol_id):
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    idol = User.query.get(idol_id)

    if idol and current_user.unfollow(idol):
        flash(f"Successfully unfollowed {idol.username}")
        return redirect(request.referrer)

    flash("Failed to unfollow user")
    return redirect(request.referrer)

instagram/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user
from instagram.users.model import User
from instagram.users.forms import NewUserForm, EditUserForm
from instagram import app, db
from instagram.helpers import upload_file_to_s3, allowed_profile_images, delete_file_from_s3
from werkzeug.utils import secure_filename


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    if current_user.is_authenticated:
        return redirect(url_for('users.edit', id=current_user.id))

    form = NewUserForm()
    return render_template('users/new.html', form=form)


@users_blueprint.route('/', methods=['POST'])
def create():
    form = NewUserForm(request.form)

    user = User(username=form.username.data,
                email=form.email.data,
                password=form.password.data)

    if len(user.validation_errors) > 0:
        return render_template('users/new.html', validation_errors=user.validation_errors, form=form)
    else:
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f"Welcome {user.username}")
        return redirect(url_for('users.show', username=user.username))


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.query.filter_by(username=username).first()

    if user:
        allowed_to_view_profile = not user.private or \
            (current_user.is_authenticated and current_user.id == user.id)
        return render_template('users/show.html', user=user, allowed_to_view_profile=allowed_to_view_profile)


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    edit_user_form = EditUserForm(obj=current_user)
    return render_template('users/edit.html', user=current_user, form=edit_user_form)


@users_blueprint.route('/<id>', methods=['POST'])
@login_required
def update(id):
    form = EditUserForm(request.form)

    user = User.query.get(id)

    # Prevent unauthorized user from changing data of another user
    if not user.id == current_user.id:
        return render_template('users/edit.html', validation_errors=['Unauthorized!'], form=form, user=user)

    user.username = form.username.data
    user.email = form.email.data
    user.description = form.description.data
    user.private = form.private.data

    if len(user.validation_errors) > 0:
        return render_template('users/edit.html', validation_errors=user.validation_errors, form=form, user=user)
    else:
        db.session.add(user)
        db.session.commit()
        flash('Information updated!')
        return redirect(url_for('users.show', username=user.username))


@users_blueprint.route('/<id>/profile/image', methods=['POST'])
@login_required
def upload_profile_image(id):
    form = EditUserForm()

    user = User.query.get(id)

    # Prevent unauthorized user from changing data of another user
    if not user.id == current_user.id:
        return render_template('users/edit.html', validation_errors=['Unauthorized!'], form=form, user=user)

    if "profile_image" not in request.files:
        flash("No profile image")
        return render_template('users/edit.html', validation_errors=[], form=form, user=user)

    file = request.files["profile_image"]

    if file.filename == "":
        flash("Please select a file")
        return render_template('users/edit.html', form=form)

    if file and allowed_profile_images(file.filename):
        old_filename = user.profile_picture
        file.filename = secure_filename(user.username + "-" + file.filename)
        output = upload_file_to_s3(file, app.config["S3_BUCKET"])
        user.profile_picture = file.filename

        db.session.add(user)
        db.session.commit()

        delete_file_from_s3(old_filename, app.config["S3_BUCKET"])

        flash("Profile Picture Updated!")

        return redirect(url_for('users.show', username=user.username))

    else:
        return redirect("/")

@users_blueprint.route('/search', methods=['POST'])
def search():
    username = request.form["username"]
    user = User.query.filter_by(username=username).first()

    return redirect(url_for("users.show", username=user.username))

instagram/templates/_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon"
    href="{{ url_for('static', filename='image/favicon.ico') }}">

    {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block header %}{% endblock %}
    <title>{% block title %}{% endblock %}Instagram Web Clone</title>
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('home')}}">
          <img src="{{ url_for('static', filename='favicon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
           Nextagram
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>

          <form class="form-inline my-2 my-lg-0" action={{url_for('users.search')}} method='POST'>
            <input class="form-control mr-sm-2" type="text" name="username" placeholder="Type username"/>
            <input type="submit" class="btn btn-outline-info my-2 my-sm-0" value="Search" />
          </form>

          <a class="nav-link" href={{url_for('users.index')}}>Users</a>

          {% if current_user.is_authenticated %}
            <a class="nav-link" href={{url_for('users.show', username=current_user.username)}}>My Profile</a>
            <a class="nav-link" href={{url_for('feed.index')}}>Feed</a>
            <a class="nav-link" href={{url_for('users.edit', id=current_user.id)}}>Edit User Profile</a>
            <form action={{url_for('sessions.sign_out')}} method='POST'>
              <input type='submit' value='Sign Out' class='btn'/>
            </form>
          {% else %}
            <a class="nav-link" href={{url_for('sessions.sign_in')}}>Sign In</a>
            <a class="nav-link" href={{url_for('users.new')}}>Sign Up</a>
          {% endif %}

          {% if current_user.fan_requests | length > 0 %}
            <a href="{{url_for('followings.show')}}" class="btn btn-primary">Follow Request <span class="badge badge-light">{{current_user.fan_requests | length}}</span></a>
          {% endif %}
        </div>
      </nav>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-primary" role="alert">
            {% for message in messages %}
              {{ message }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      {% endwith %}
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>