instagram/blueprints/followings/views.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_login import current_user
from models.user import User

followings_blueprint = Blueprint('followings',
                            __name__,
                            template_folder='templates')


@followings_blueprint.route('/', methods=['GET'])
def show():
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    return render_template('followings/show.html')

@followings_blueprint.route('/', methods=['POST'])
def create():
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    fan_id = request.form.get('fan_id')

    if fan_id:
        fan = User.query.get(fan_id)
        if fan and current_user.approve(fan):
            print("------------")
            flash(f"You've approved {fan.username}")
            return redirect(request.referrer)

    idol = User.query.get(request.form['idol_id'])

    if idol and current_user.follow(idol) == 'Your request has been sent':
        flash(f"Your request to follow {idol.username} has been sent")
        return redirect(request.referrer)

    elif idol and current_user.follow(idol):
        flash(f"Successfully followed {idol.username}")
        return redirect(request.referrer)

    flash("Failed to follow user")
    return redirect(request.referrer)

@followings_blueprint.route('/<idol_id>', methods=['POST'])
def destroy(idol_id):
    if not current_user.is_authenticated:
        flash("Sign in first")
        return redirect(url_for('sessions.sign_in'))

    idol = User.query.get(idol_id)

    if idol and current_user.unfollow(idol):
        flash(f"Successfully unfollowed {idol.username}")
        return redirect(request.referrer)

    flash("Failed to unfollow user")
    return redirect(request.referrer)

instagram/blueprints/followings/templates/followings/show.html
{% extends "_base.html" %}
{% block title %}Your followers | {% endblock %}
{% block content %}
  <h4 class="mt-4">You have Nextagrammers who wants to follow you!</h2>
  <div class="d-flex flex-wrap bd-highlight mt-5 mb-3">
    {% for following_request in current_user.fan_requests %}
      <div class="flex-fill card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">
            <a href={{url_for("users.show", username=following_request.username)}} class="font-weight-bold">{{following_request.username}}</a>
          </h5>
          <img src="{{following_request.profile_picture_url}}" class="follower-image rounded-circle" />
          <p class="mt-3 mb-3 card-text">{{following_request.description}}</p>
          <div class="clearfix">
            <form method="POST" action={{url_for("followings.create")}}>
              <input type="hidden" name="fan_id" value="{{following_request.id}}">
              <input type="submit" class="btn btn-info btn-block text-center" value="Approve">
            </form>
          </div>

        </div>
      </div>
    {% endfor %}
  </div>


{% endblock %}